version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
